all:
  children:
    web:
      hosts:
        web01:
          ansible_host: 172.30.1.201
        web-test:
          ansible_host: 172.30.1.205
    was:
      hosts:
        was01:
          ansible_host: 172.30.1.202
        was-test:
          ansible_host: 172.30.1.206
    dns:
      hosts:
        dns01:
          ansible_host: 172.30.1.204
    db:
      hosts:
        db01:
          ansible_host: 172.30.1.203
          ansible_user: lee
  vars:
    ansible_user: root
