- name: dnsmasq 설치
  package:
    name: dnsmasq
    state: present

- name: dnsmasq 설정 배포
  template:
    src: homelab.conf.j2
    dest: /etc/dnsmasq.d/homelab.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart dnsmasq

- name: dns 레코드 배포
  template:
    src: dnsmasq.hosts.j2
    dest: /etc/dnsmasq.hosts
    owner: root
    group: root
    mode: '0644'
  notify: restart dnsmasq

- name: dnsmasq 서비스 시작 및 자동시작 등록
  service:
    name: dnsmasq
    state: started
    enabled: yes
